    procedure,private :: utest_less_byte_00
    procedure,private :: utest_less_byte_01
    procedure,private :: utest_less_byte_10
    procedure,private :: utest_less_byte_11
    procedure,private :: utest_less_int2_00
    procedure,private :: utest_less_int2_01
    procedure,private :: utest_less_int2_10
    procedure,private :: utest_less_int2_11
    procedure,private :: utest_less_int4_00
    procedure,private :: utest_less_int4_01
    procedure,private :: utest_less_int4_10
    procedure,private :: utest_less_int4_11
    procedure,private :: utest_less_int8_00
    procedure,private :: utest_less_int8_01
    procedure,private :: utest_less_int8_10
    procedure,private :: utest_less_int8_11
    procedure,private :: utest_less_real_00
    procedure,private :: utest_less_real_01
    procedure,private :: utest_less_real_10
    procedure,private :: utest_less_real_11
    procedure,private :: utest_less_dble_00
    procedure,private :: utest_less_dble_01
    procedure,private :: utest_less_dble_10
    procedure,private :: utest_less_dble_11
    procedure,private :: utest_less_quad_00
    procedure,private :: utest_less_quad_01
    procedure,private :: utest_less_quad_10
    procedure,private :: utest_less_quad_11
    generic           :: assert_less =>      &
                       & utest_less_byte_00, &
                       & utest_less_byte_01, &
                       & utest_less_byte_10, &
                       & utest_less_byte_11, &
                       & utest_less_int2_00, &
                       & utest_less_int2_01, &
                       & utest_less_int2_10, &
                       & utest_less_int2_11, &
                       & utest_less_int4_00, &
                       & utest_less_int4_01, &
                       & utest_less_int4_10, &
                       & utest_less_int4_11, &
                       & utest_less_int8_00, &
                       & utest_less_int8_01, &
                       & utest_less_int8_10, &
                       & utest_less_int8_11, &
                       & utest_less_real_00, &
                       & utest_less_real_01, &
                       & utest_less_real_10, &
                       & utest_less_real_11, &
                       & utest_less_dble_00, &
                       & utest_less_dble_01, &
                       & utest_less_dble_10, &
                       & utest_less_dble_11, &
                       & utest_less_quad_00, &
                       & utest_less_quad_01, &
                       & utest_less_quad_10, &
                       & utest_less_quad_11
    procedure,private :: utest_less_equal_byte_00
    procedure,private :: utest_less_equal_byte_01
    procedure,private :: utest_less_equal_byte_10
    procedure,private :: utest_less_equal_byte_11
    procedure,private :: utest_less_equal_int2_00
    procedure,private :: utest_less_equal_int2_01
    procedure,private :: utest_less_equal_int2_10
    procedure,private :: utest_less_equal_int2_11
    procedure,private :: utest_less_equal_int4_00
    procedure,private :: utest_less_equal_int4_01
    procedure,private :: utest_less_equal_int4_10
    procedure,private :: utest_less_equal_int4_11
    procedure,private :: utest_less_equal_int8_00
    procedure,private :: utest_less_equal_int8_01
    procedure,private :: utest_less_equal_int8_10
    procedure,private :: utest_less_equal_int8_11
    procedure,private :: utest_less_equal_real_00
    procedure,private :: utest_less_equal_real_01
    procedure,private :: utest_less_equal_real_10
    procedure,private :: utest_less_equal_real_11
    procedure,private :: utest_less_equal_dble_00
    procedure,private :: utest_less_equal_dble_01
    procedure,private :: utest_less_equal_dble_10
    procedure,private :: utest_less_equal_dble_11
    procedure,private :: utest_less_equal_quad_00
    procedure,private :: utest_less_equal_quad_01
    procedure,private :: utest_less_equal_quad_10
    procedure,private :: utest_less_equal_quad_11
    generic           :: assert_less_equal =>      &
                       & utest_less_equal_byte_00, &
                       & utest_less_equal_byte_01, &
                       & utest_less_equal_byte_10, &
                       & utest_less_equal_byte_11, &
                       & utest_less_equal_int2_00, &
                       & utest_less_equal_int2_01, &
                       & utest_less_equal_int2_10, &
                       & utest_less_equal_int2_11, &
                       & utest_less_equal_int4_00, &
                       & utest_less_equal_int4_01, &
                       & utest_less_equal_int4_10, &
                       & utest_less_equal_int4_11, &
                       & utest_less_equal_int8_00, &
                       & utest_less_equal_int8_01, &
                       & utest_less_equal_int8_10, &
                       & utest_less_equal_int8_11, &
                       & utest_less_equal_real_00, &
                       & utest_less_equal_real_01, &
                       & utest_less_equal_real_10, &
                       & utest_less_equal_real_11, &
                       & utest_less_equal_dble_00, &
                       & utest_less_equal_dble_01, &
                       & utest_less_equal_dble_10, &
                       & utest_less_equal_dble_11, &
                       & utest_less_equal_quad_00, &
                       & utest_less_equal_quad_01, &
                       & utest_less_equal_quad_10, &
                       & utest_less_equal_quad_11
    procedure,private :: utest_greater_byte_00
    procedure,private :: utest_greater_byte_01
    procedure,private :: utest_greater_byte_10
    procedure,private :: utest_greater_byte_11
    procedure,private :: utest_greater_int2_00
    procedure,private :: utest_greater_int2_01
    procedure,private :: utest_greater_int2_10
    procedure,private :: utest_greater_int2_11
    procedure,private :: utest_greater_int4_00
    procedure,private :: utest_greater_int4_01
    procedure,private :: utest_greater_int4_10
    procedure,private :: utest_greater_int4_11
    procedure,private :: utest_greater_int8_00
    procedure,private :: utest_greater_int8_01
    procedure,private :: utest_greater_int8_10
    procedure,private :: utest_greater_int8_11
    procedure,private :: utest_greater_real_00
    procedure,private :: utest_greater_real_01
    procedure,private :: utest_greater_real_10
    procedure,private :: utest_greater_real_11
    procedure,private :: utest_greater_dble_00
    procedure,private :: utest_greater_dble_01
    procedure,private :: utest_greater_dble_10
    procedure,private :: utest_greater_dble_11
    procedure,private :: utest_greater_quad_00
    procedure,private :: utest_greater_quad_01
    procedure,private :: utest_greater_quad_10
    procedure,private :: utest_greater_quad_11
    generic           :: assert_greater =>      &
                       & utest_greater_byte_00, &
                       & utest_greater_byte_01, &
                       & utest_greater_byte_10, &
                       & utest_greater_byte_11, &
                       & utest_greater_int2_00, &
                       & utest_greater_int2_01, &
                       & utest_greater_int2_10, &
                       & utest_greater_int2_11, &
                       & utest_greater_int4_00, &
                       & utest_greater_int4_01, &
                       & utest_greater_int4_10, &
                       & utest_greater_int4_11, &
                       & utest_greater_int8_00, &
                       & utest_greater_int8_01, &
                       & utest_greater_int8_10, &
                       & utest_greater_int8_11, &
                       & utest_greater_real_00, &
                       & utest_greater_real_01, &
                       & utest_greater_real_10, &
                       & utest_greater_real_11, &
                       & utest_greater_dble_00, &
                       & utest_greater_dble_01, &
                       & utest_greater_dble_10, &
                       & utest_greater_dble_11, &
                       & utest_greater_quad_00, &
                       & utest_greater_quad_01, &
                       & utest_greater_quad_10, &
                       & utest_greater_quad_11
    procedure,private :: utest_greater_equal_byte_00
    procedure,private :: utest_greater_equal_byte_01
    procedure,private :: utest_greater_equal_byte_10
    procedure,private :: utest_greater_equal_byte_11
    procedure,private :: utest_greater_equal_int2_00
    procedure,private :: utest_greater_equal_int2_01
    procedure,private :: utest_greater_equal_int2_10
    procedure,private :: utest_greater_equal_int2_11
    procedure,private :: utest_greater_equal_int4_00
    procedure,private :: utest_greater_equal_int4_01
    procedure,private :: utest_greater_equal_int4_10
    procedure,private :: utest_greater_equal_int4_11
    procedure,private :: utest_greater_equal_int8_00
    procedure,private :: utest_greater_equal_int8_01
    procedure,private :: utest_greater_equal_int8_10
    procedure,private :: utest_greater_equal_int8_11
    procedure,private :: utest_greater_equal_real_00
    procedure,private :: utest_greater_equal_real_01
    procedure,private :: utest_greater_equal_real_10
    procedure,private :: utest_greater_equal_real_11
    procedure,private :: utest_greater_equal_dble_00
    procedure,private :: utest_greater_equal_dble_01
    procedure,private :: utest_greater_equal_dble_10
    procedure,private :: utest_greater_equal_dble_11
    procedure,private :: utest_greater_equal_quad_00
    procedure,private :: utest_greater_equal_quad_01
    procedure,private :: utest_greater_equal_quad_10
    procedure,private :: utest_greater_equal_quad_11
    generic           :: assert_greater_equal =>      &
                       & utest_greater_equal_byte_00, &
                       & utest_greater_equal_byte_01, &
                       & utest_greater_equal_byte_10, &
                       & utest_greater_equal_byte_11, &
                       & utest_greater_equal_int2_00, &
                       & utest_greater_equal_int2_01, &
                       & utest_greater_equal_int2_10, &
                       & utest_greater_equal_int2_11, &
                       & utest_greater_equal_int4_00, &
                       & utest_greater_equal_int4_01, &
                       & utest_greater_equal_int4_10, &
                       & utest_greater_equal_int4_11, &
                       & utest_greater_equal_int8_00, &
                       & utest_greater_equal_int8_01, &
                       & utest_greater_equal_int8_10, &
                       & utest_greater_equal_int8_11, &
                       & utest_greater_equal_real_00, &
                       & utest_greater_equal_real_01, &
                       & utest_greater_equal_real_10, &
                       & utest_greater_equal_real_11, &
                       & utest_greater_equal_dble_00, &
                       & utest_greater_equal_dble_01, &
                       & utest_greater_equal_dble_10, &
                       & utest_greater_equal_dble_11, &
                       & utest_greater_equal_quad_00, &
                       & utest_greater_equal_quad_01, &
                       & utest_greater_equal_quad_10, &
                       & utest_greater_equal_quad_11
    procedure,private :: utest_almost_equal_byte_00
    procedure,private :: utest_almost_equal_byte_01
    procedure,private :: utest_almost_equal_byte_10
    procedure,private :: utest_almost_equal_byte_11
    procedure,private :: utest_almost_equal_int2_00
    procedure,private :: utest_almost_equal_int2_01
    procedure,private :: utest_almost_equal_int2_10
    procedure,private :: utest_almost_equal_int2_11
    procedure,private :: utest_almost_equal_int4_00
    procedure,private :: utest_almost_equal_int4_01
    procedure,private :: utest_almost_equal_int4_10
    procedure,private :: utest_almost_equal_int4_11
    procedure,private :: utest_almost_equal_int8_00
    procedure,private :: utest_almost_equal_int8_01
    procedure,private :: utest_almost_equal_int8_10
    procedure,private :: utest_almost_equal_int8_11
    procedure,private :: utest_almost_equal_real_00
    procedure,private :: utest_almost_equal_real_01
    procedure,private :: utest_almost_equal_real_10
    procedure,private :: utest_almost_equal_real_11
    procedure,private :: utest_almost_equal_dble_00
    procedure,private :: utest_almost_equal_dble_01
    procedure,private :: utest_almost_equal_dble_10
    procedure,private :: utest_almost_equal_dble_11
    procedure,private :: utest_almost_equal_quad_00
    procedure,private :: utest_almost_equal_quad_01
    procedure,private :: utest_almost_equal_quad_10
    procedure,private :: utest_almost_equal_quad_11
    generic           :: assert_almost_equal =>      &
                       & utest_almost_equal_byte_00, &
                       & utest_almost_equal_byte_01, &
                       & utest_almost_equal_byte_10, &
                       & utest_almost_equal_byte_11, &
                       & utest_almost_equal_int2_00, &
                       & utest_almost_equal_int2_01, &
                       & utest_almost_equal_int2_10, &
                       & utest_almost_equal_int2_11, &
                       & utest_almost_equal_int4_00, &
                       & utest_almost_equal_int4_01, &
                       & utest_almost_equal_int4_10, &
                       & utest_almost_equal_int4_11, &
                       & utest_almost_equal_int8_00, &
                       & utest_almost_equal_int8_01, &
                       & utest_almost_equal_int8_10, &
                       & utest_almost_equal_int8_11, &
                       & utest_almost_equal_real_00, &
                       & utest_almost_equal_real_01, &
                       & utest_almost_equal_real_10, &
                       & utest_almost_equal_real_11, &
                       & utest_almost_equal_dble_00, &
                       & utest_almost_equal_dble_01, &
                       & utest_almost_equal_dble_10, &
                       & utest_almost_equal_dble_11, &
                       & utest_almost_equal_quad_00, &
                       & utest_almost_equal_quad_01, &
                       & utest_almost_equal_quad_10, &
                       & utest_almost_equal_quad_11
    procedure,private :: utest_not_almost_equal_byte_00
    procedure,private :: utest_not_almost_equal_byte_01
    procedure,private :: utest_not_almost_equal_byte_10
    procedure,private :: utest_not_almost_equal_byte_11
    procedure,private :: utest_not_almost_equal_int2_00
    procedure,private :: utest_not_almost_equal_int2_01
    procedure,private :: utest_not_almost_equal_int2_10
    procedure,private :: utest_not_almost_equal_int2_11
    procedure,private :: utest_not_almost_equal_int4_00
    procedure,private :: utest_not_almost_equal_int4_01
    procedure,private :: utest_not_almost_equal_int4_10
    procedure,private :: utest_not_almost_equal_int4_11
    procedure,private :: utest_not_almost_equal_int8_00
    procedure,private :: utest_not_almost_equal_int8_01
    procedure,private :: utest_not_almost_equal_int8_10
    procedure,private :: utest_not_almost_equal_int8_11
    procedure,private :: utest_not_almost_equal_real_00
    procedure,private :: utest_not_almost_equal_real_01
    procedure,private :: utest_not_almost_equal_real_10
    procedure,private :: utest_not_almost_equal_real_11
    procedure,private :: utest_not_almost_equal_dble_00
    procedure,private :: utest_not_almost_equal_dble_01
    procedure,private :: utest_not_almost_equal_dble_10
    procedure,private :: utest_not_almost_equal_dble_11
    procedure,private :: utest_not_almost_equal_quad_00
    procedure,private :: utest_not_almost_equal_quad_01
    procedure,private :: utest_not_almost_equal_quad_10
    procedure,private :: utest_not_almost_equal_quad_11
    generic           :: assert_not_almost_equal =>      &
                       & utest_not_almost_equal_byte_00, &
                       & utest_not_almost_equal_byte_01, &
                       & utest_not_almost_equal_byte_10, &
                       & utest_not_almost_equal_byte_11, &
                       & utest_not_almost_equal_int2_00, &
                       & utest_not_almost_equal_int2_01, &
                       & utest_not_almost_equal_int2_10, &
                       & utest_not_almost_equal_int2_11, &
                       & utest_not_almost_equal_int4_00, &
                       & utest_not_almost_equal_int4_01, &
                       & utest_not_almost_equal_int4_10, &
                       & utest_not_almost_equal_int4_11, &
                       & utest_not_almost_equal_int8_00, &
                       & utest_not_almost_equal_int8_01, &
                       & utest_not_almost_equal_int8_10, &
                       & utest_not_almost_equal_int8_11, &
                       & utest_not_almost_equal_real_00, &
                       & utest_not_almost_equal_real_01, &
                       & utest_not_almost_equal_real_10, &
                       & utest_not_almost_equal_real_11, &
                       & utest_not_almost_equal_dble_00, &
                       & utest_not_almost_equal_dble_01, &
                       & utest_not_almost_equal_dble_10, &
                       & utest_not_almost_equal_dble_11, &
                       & utest_not_almost_equal_quad_00, &
                       & utest_not_almost_equal_quad_01, &
                       & utest_not_almost_equal_quad_10, &
                       & utest_not_almost_equal_quad_11
