    procedure,private :: utest_almost_equal_cmp4_00
    procedure,private :: utest_almost_equal_cmp4_01
    procedure,private :: utest_almost_equal_cmp4_10
    procedure,private :: utest_almost_equal_cmp4_11
    procedure,private :: utest_almost_equal_cmp8_00
    procedure,private :: utest_almost_equal_cmp8_01
    procedure,private :: utest_almost_equal_cmp8_10
    procedure,private :: utest_almost_equal_cmp8_11
    procedure,private :: utest_almost_equal_cmp16_00
    procedure,private :: utest_almost_equal_cmp16_01
    procedure,private :: utest_almost_equal_cmp16_10
    procedure,private :: utest_almost_equal_cmp16_11
    generic           :: assert_almost_equal =>      &
                       & utest_almost_equal_cmp4_00, &
                       & utest_almost_equal_cmp4_01, &
                       & utest_almost_equal_cmp4_10, &
                       & utest_almost_equal_cmp4_11, &
                       & utest_almost_equal_cmp8_00, &
                       & utest_almost_equal_cmp8_01, &
                       & utest_almost_equal_cmp8_10, &
                       & utest_almost_equal_cmp8_11, &
                       & utest_almost_equal_cmp16_00, &
                       & utest_almost_equal_cmp16_01, &
                       & utest_almost_equal_cmp16_10, &
                       & utest_almost_equal_cmp16_11
    procedure,private :: utest_not_almost_equal_cmp4_00
    procedure,private :: utest_not_almost_equal_cmp4_01
    procedure,private :: utest_not_almost_equal_cmp4_10
    procedure,private :: utest_not_almost_equal_cmp4_11
    procedure,private :: utest_not_almost_equal_cmp8_00
    procedure,private :: utest_not_almost_equal_cmp8_01
    procedure,private :: utest_not_almost_equal_cmp8_10
    procedure,private :: utest_not_almost_equal_cmp8_11
    procedure,private :: utest_not_almost_equal_cmp16_00
    procedure,private :: utest_not_almost_equal_cmp16_01
    procedure,private :: utest_not_almost_equal_cmp16_10
    procedure,private :: utest_not_almost_equal_cmp16_11
    generic           :: assert_not_almost_equal =>      &
                       & utest_not_almost_equal_cmp4_00, &
                       & utest_not_almost_equal_cmp4_01, &
                       & utest_not_almost_equal_cmp4_10, &
                       & utest_not_almost_equal_cmp4_11, &
                       & utest_not_almost_equal_cmp8_00, &
                       & utest_not_almost_equal_cmp8_01, &
                       & utest_not_almost_equal_cmp8_10, &
                       & utest_not_almost_equal_cmp8_11, &
                       & utest_not_almost_equal_cmp16_00, &
                       & utest_not_almost_equal_cmp16_01, &
                       & utest_not_almost_equal_cmp16_10, &
                       & utest_not_almost_equal_cmp16_11
