name: Build and Deploy Documentation

on: [push, pull_request]

env:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  PIP_DISABLE_PIP_VERSION_CHECK: "ON"
  PIP_NO_CLEAN: "ON"
  PIP_PREFER_BINARY: "ON"
  TZ: "UTC"

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -v ford==7.0.5
        pip install fypp
        python --version
        ford --version
        fypp --version

    - name: Build Developer Documentation
      run: |
        ford doc/api-doc-ford-settings.md
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: doc/api-doc
        if-no-files-found: error

    - name: Broken Link Check
      if: ${{ github.ref == 'refs/heads/main'}}
      uses: technote-space/broken-link-checker-action@v1
      with:
        TARGET: file://${{ github.workspace }}/api-doc/index.html
        RECURSIVE: true
        ASSIGNEES: ${{ github.actor }}

    - name: Deploy API Documentation
      uses: JamesIves/github-pages-deploy-action@4.1.0
      if: github.event_name == 'push' && github.repository == 'yymmt742/unittest' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/master' )
      with:
        branch: gh-pages
        folder: doc/api-doc
        commit_message: "From https://github.com/${{ github.repository }}/commit/${{ github.sha }} ${{ github.ref }}"
